export const RBAC_ACTION_KEYS = [
  'view',
  'read',
  'create',
  'edit',
  'delete',
  'export',
  'import',
  'approve',
  'assign',
  'manage',
];

const resource = ({
  key,
  name,
  path,
  paths = [],
  description = '',
  actions = [],
  sidebarVisible = true,
  displayOrder = 0,
}) => ({
  key,
  name,
  path,
  paths,
  description,
  actions,
  sidebarVisible,
  displayOrder,
});

const defineModule = ({
  key,
  name,
  slug,
  description = '',
  icon = '',
  category = 'core',
  sidebarVisible = true,
  displayOrder = 0,
  dependencies = [],
  features = [],
  resources = [],
}) => ({
  key,
  name,
  slug,
  description,
  icon,
  category,
  sidebarVisible,
  displayOrder,
  dependencies,
  features,
  resources,
});

export const RBAC_MODULES = [
  defineModule({
    key: 'core',
    name: 'Core',
    slug: 'core',
    description: 'Shared dashboard, profile, and personal settings pages',
    icon: 'dashboard',
    category: 'shared',
    displayOrder: 1,
    resources: [
      resource({
        key: 'dashboard',
        name: 'Dashboard',
        path: '/dashboard',
        paths: ['/dashboard', '/admin/dashboard', '/super-admin/dashboard'],
        description: 'Role-specific dashboard overview',
        actions: ['view', 'read'],
      }),
      resource({
        key: 'profile',
        name: 'My Profile',
        path: '/user/profile',
        paths: ['/user/profile', '/user/profile/edit'],
        description: 'Personal profile information and preferences',
        actions: ['view', 'read', 'edit'],
      }),
      resource({
        key: 'settings',
        name: 'Settings',
        path: '/user/settings',
        paths: ['/user/settings', '/admin/settings', '/super-admin/settings', '/super-admin/system-settings'],
        description: 'Personal and application settings pages',
        actions: ['view', 'read', 'edit'],
      }),
    ],
  }),
  defineModule({
    key: 'administration',
    name: 'Administration',
    slug: 'administration',
    description: 'User, role, department, and platform administration tools',
    icon: 'shield',
    category: 'system',
    displayOrder: 2,
    resources: [
      resource({
        key: 'users',
        name: 'Users',
        path: '/super-admin/users',
        paths: ['/super-admin/users'],
        description: 'Application account management',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
      }),
      resource({
        key: 'roles_permissions',
        name: 'Roles & Permissions',
        path: '/super-admin/roles-permissions',
        paths: ['/super-admin/roles-permissions'],
        description: 'Central RBAC role and permission management',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
      }),
      resource({
        key: 'modules',
        name: 'Modules',
        path: '/super-admin/modules',
        paths: ['/super-admin/modules'],
        description: 'Platform module catalog and visibility control',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
      }),
      resource({
        key: 'departments',
        name: 'Departments',
        path: '/admin/departments',
        paths: ['/admin/departments', '/super-admin/departments'],
        description: 'Company department management',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
      }),
      resource({
        key: 'employees',
        name: 'Employees',
        path: '/admin/employees',
        paths: ['/admin/employees'],
        description: 'Employee directory and HR records',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
      }),
    ],
  }),
  defineModule({
    key: 'crm',
    name: 'CRM',
    slug: 'crm',
    description: 'Lead and client management tools',
    icon: 'crm',
    category: 'business',
    displayOrder: 3,
    resources: [
      resource({
        key: 'crm_overview',
        name: 'CRM Overview',
        path: '/super-admin/crm',
        paths: ['/super-admin/crm'],
        description: 'CRM overview dashboard',
        actions: ['view', 'read'],
      }),
      resource({
        key: 'leads',
        name: 'Leads',
        path: '/user/leads',
        paths: ['/user/leads', '/admin/leads'],
        description: 'Lead pipeline and follow-up records',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'export', 'assign'],
      }),
      resource({
        key: 'clients',
        name: 'Clients',
        path: '/user/clients',
        paths: ['/user/clients', '/admin/clients'],
        description: 'Client records and account history',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'export', 'assign'],
      }),
    ],
  }),
  defineModule({
    key: 'projects',
    name: 'Projects',
    slug: 'projects',
    description: 'Project and task delivery workspace',
    icon: 'project',
    category: 'business',
    displayOrder: 4,
    resources: [
      resource({
        key: 'projects',
        name: 'Projects',
        path: '/user/projects',
        paths: ['/user/projects', '/admin/projects', '/super-admin/projects'],
        description: 'Project planning and execution',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'export', 'assign', 'manage'],
      }),
      resource({
        key: 'tasks',
        name: 'Tasks',
        path: '/user/tasks',
        paths: ['/user/tasks', '/admin/tasks'],
        description: 'Task assignment and progress tracking',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'assign', 'manage'],
      }),
    ],
  }),
  defineModule({
    key: 'hrms',
    name: 'HRMS',
    slug: 'hrms',
    description: 'Attendance, leave, and employee lifecycle management',
    icon: 'users',
    category: 'business',
    displayOrder: 5,
    resources: [
      resource({
        key: 'hrms_overview',
        name: 'HRMS Overview',
        path: '/super-admin/hrms',
        paths: ['/super-admin/hrms'],
        description: 'HRMS overview dashboard',
        actions: ['view', 'read'],
      }),
      resource({
        key: 'attendance',
        name: 'Attendance',
        path: '/user/attendance',
        paths: ['/user/attendance', '/admin/attendance'],
        description: 'Attendance records and check-in flows',
        actions: ['view', 'read', 'create', 'edit', 'approve', 'manage'],
      }),
      resource({
        key: 'leave_requests',
        name: 'Leave Requests',
        path: '/user/leave-requests',
        paths: ['/user/leave-requests', '/admin/leave-requests'],
        description: 'Leave submission and approval workflow',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'approve', 'manage'],
      }),
      resource({
        key: 'hr_support',
        name: 'HR Support',
        path: '/user/hr-support',
        paths: ['/user/hr-support'],
        description: 'Employee HR helpdesk and case management',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'assign', 'manage'],
      }),
    ],
  }),
  defineModule({
    key: 'finance',
    name: 'Finance',
    slug: 'finance',
    description: 'Payroll and invoice management',
    icon: 'finance',
    category: 'business',
    displayOrder: 6,
    resources: [
      resource({
        key: 'payroll',
        name: 'Payroll',
        path: '/user/payroll',
        paths: ['/user/payroll', '/admin/payroll', '/super-admin/payroll'],
        description: 'Salary processing and payment records',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'approve', 'export', 'manage'],
      }),
      resource({
        key: 'invoices',
        name: 'Invoices',
        path: '/user/invoices',
        paths: ['/user/invoices'],
        description: 'Invoice records and billing workflow',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'export', 'manage'],
      }),
    ],
  }),
  defineModule({
    key: 'documents',
    name: 'Documents',
    slug: 'documents',
    description: 'Document storage and file management',
    icon: 'document',
    category: 'business',
    displayOrder: 7,
    resources: [
      resource({
        key: 'documents',
        name: 'Documents',
        path: '/user/documents',
        paths: ['/user/documents', '/admin/documents'],
        description: 'Document upload, download, and deletion',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'export', 'import', 'manage'],
      }),
    ],
  }),
  defineModule({
    key: 'communications',
    name: 'Communications',
    slug: 'communications',
    description: 'Notifications, announcements, and calendar coordination',
    icon: 'communication',
    category: 'business',
    displayOrder: 8,
    resources: [
      resource({
        key: 'notifications',
        name: 'Notifications',
        path: '/user/notifications',
        paths: ['/user/notifications', '/admin/notifications', '/super-admin/notifications'],
        description: 'In-app notification feeds and broadcast alerts',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
      }),
      resource({
        key: 'announcements',
        name: 'Announcements',
        path: '/admin/announcements',
        paths: ['/admin/announcements'],
        description: 'Company announcements and broadcasts',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
      }),
      resource({
        key: 'calendar',
        name: 'Calendar',
        path: '/user/calendar',
        paths: ['/user/calendar', '/admin/calendar'],
        description: 'Shared calendar events and scheduling',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
      }),
    ],
  }),
  defineModule({
    key: 'reports',
    name: 'Reports',
    slug: 'reports',
    description: 'Operational reports and audit trails',
    icon: 'reports',
    category: 'system',
    displayOrder: 9,
    resources: [
      resource({
        key: 'reports',
        name: 'Reports',
        path: '/admin/reports',
        paths: ['/admin/reports', '/super-admin/reports'],
        description: 'Business reporting dashboards',
        actions: ['view', 'read', 'export', 'manage'],
      }),
      resource({
        key: 'activity_logs',
        name: 'Activity Logs',
        path: '/super-admin/activity-logs',
        paths: ['/super-admin/activity-logs'],
        description: 'System and user activity history',
        actions: ['view', 'read', 'export'],
      }),
      resource({
        key: 'audit_logs',
        name: 'Audit Logs',
        path: '/super-admin/audit-logs',
        paths: ['/super-admin/audit-logs'],
        description: 'Audit trail for critical platform actions',
        actions: ['view', 'read', 'export'],
      }),
    ],
  }),
  defineModule({
    key: 'system',
    name: 'System',
    slug: 'system',
    description: 'Platform-level controls and integrations',
    icon: 'system',
    category: 'system',
    displayOrder: 10,
    resources: [
      resource({
        key: 'system_settings',
        name: 'System Settings',
        path: '/super-admin/system-settings',
        paths: ['/super-admin/system-settings'],
        description: 'Platform-wide system settings',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
      }),
      resource({
        key: 'database_backup',
        name: 'Database Backup',
        path: '/super-admin/database-backup',
        paths: ['/super-admin/database-backup'],
        description: 'Database backup and restore utilities',
        actions: ['view', 'read', 'create', 'delete', 'manage'],
      }),
      resource({
        key: 'api_integrations',
        name: 'API Integrations',
        path: '/super-admin/api-integrations',
        paths: ['/super-admin/api-integrations'],
        description: 'External integrations and API settings',
        actions: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
      }),
    ],
  }),
];

export const RBAC_ROLE_KEYS = ['super_admin', 'admin', 'manager', 'employee'];

export const RBAC_ROLE_DEFAULTS = [
  {
    key: 'super_admin',
    name: 'Super Admin',
    description: 'Full access to every module, resource, and action',
    type: 'system',
    status: 'Active',
    isProtected: true,
    isSystem: true,
    parentKey: null,
    sortOrder: 1,
  },
  {
    key: 'admin',
    name: 'Admin',
    description: 'Operational administrator with access to company workflows',
    type: 'system',
    status: 'Active',
    isProtected: false,
    isSystem: true,
    parentKey: 'super_admin',
    sortOrder: 2,
  },
  {
    key: 'manager',
    name: 'Manager',
    description: 'Safe management access for team-level operations',
    type: 'system',
    status: 'Active',
    isProtected: false,
    isSystem: true,
    parentKey: 'admin',
    sortOrder: 3,
  },
  {
    key: 'employee',
    name: 'Employee',
    description: 'Personal workspace and own-record access',
    type: 'system',
    status: 'Active',
    isProtected: false,
    isSystem: true,
    parentKey: 'manager',
    sortOrder: 4,
  },
];

export const RBAC_ROLE_TEMPLATES = {
  super_admin: {
    moduleEnabled: () => true,
    resourceActions: () => RBAC_ACTION_KEYS,
  },
  admin: {
    moduleEnabled: (moduleKey) => ['core', 'administration', 'crm', 'projects', 'hrms', 'finance', 'documents', 'communications', 'reports'].includes(moduleKey),
    resourceActions: ({ resourceKey }) => {
      const map = {
        dashboard: ['view', 'read'],
        profile: ['view', 'read', 'edit'],
        settings: ['view', 'read', 'edit'],
        users: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
        roles_permissions: ['view', 'read', 'create', 'edit', 'manage'],
        modules: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
        departments: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
        employees: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
        crm_overview: ['view', 'read'],
        leads: ['view', 'read', 'create', 'edit', 'delete', 'export', 'assign', 'manage'],
        clients: ['view', 'read', 'create', 'edit', 'delete', 'export', 'assign', 'manage'],
        projects: ['view', 'read', 'create', 'edit', 'delete', 'export', 'assign', 'manage'],
        tasks: ['view', 'read', 'create', 'edit', 'delete', 'assign', 'manage'],
        hrms_overview: ['view', 'read'],
        attendance: ['view', 'read', 'create', 'edit', 'approve', 'manage'],
        leave_requests: ['view', 'read', 'create', 'edit', 'delete', 'approve', 'manage'],
        payroll: ['view', 'read', 'create', 'edit', 'delete', 'approve', 'export', 'manage'],
        invoices: ['view', 'read', 'create', 'edit', 'delete', 'export', 'manage'],
        documents: ['view', 'read', 'create', 'edit', 'delete', 'export', 'import', 'manage'],
        notifications: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
        announcements: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
        calendar: ['view', 'read', 'create', 'edit', 'delete', 'manage'],
        reports: ['view', 'read', 'export', 'manage'],
        activity_logs: ['view', 'read', 'export'],
        audit_logs: ['view', 'read', 'export'],
      };
      return map[resourceKey] || ['view', 'read'];
    },
  },
  manager: {
    moduleEnabled: (moduleKey) => ['core', 'crm', 'projects', 'hrms', 'finance', 'documents', 'communications', 'reports'].includes(moduleKey),
    resourceActions: ({ resourceKey }) => {
      const map = {
        dashboard: ['view', 'read'],
        profile: ['view', 'read', 'edit'],
        settings: ['view', 'read', 'edit'],
        leads: ['view', 'read', 'create', 'edit', 'export'],
        clients: ['view', 'read', 'create', 'edit', 'export'],
        projects: ['view', 'read', 'create', 'edit', 'assign'],
        tasks: ['view', 'read', 'create', 'edit', 'assign'],
        attendance: ['view', 'read', 'edit'],
        leave_requests: ['view', 'read', 'create', 'edit', 'approve'],
        payroll: ['view', 'read'],
        invoices: ['view', 'read'],
        documents: ['view', 'read', 'create', 'edit'],
        notifications: ['view', 'read'],
        announcements: ['view', 'read'],
        calendar: ['view', 'read', 'create', 'edit'],
        reports: ['view', 'read', 'export'],
      };
      return map[resourceKey] || ['view', 'read'];
    },
  },
  employee: {
    moduleEnabled: (moduleKey) => ['core', 'crm', 'projects', 'hrms', 'finance', 'documents', 'communications'].includes(moduleKey),
    resourceActions: ({ resourceKey }) => {
      const map = {
        dashboard: ['view', 'read'],
        profile: ['view', 'read', 'edit'],
        settings: ['view', 'read', 'edit'],
        leads: ['view', 'read', 'create', 'edit', 'delete'],
        clients: ['view', 'read', 'create', 'edit', 'delete'],
        projects: ['view', 'read', 'create', 'edit', 'delete'],
        tasks: ['view', 'read', 'create', 'edit', 'delete'],
        attendance: ['view', 'read', 'create', 'edit'],
        leave_requests: ['view', 'read', 'create', 'edit', 'delete'],
        payroll: ['view', 'read'],
        invoices: ['view', 'read'],
        documents: ['view', 'read', 'create', 'edit', 'delete'],
        notifications: ['view', 'read'],
        calendar: ['view', 'read'],
      };
      return map[resourceKey] || ['view', 'read'];
    },
  },
};

export const buildActionState = (allowedActions = []) =>
  Object.fromEntries(RBAC_ACTION_KEYS.map((action) => [action, allowedActions.includes(action)]));

export const buildEmptyActionState = () => buildActionState([]);

export const getAllResourceDefinitions = () =>
  RBAC_MODULES.flatMap((rbacModule) =>
    rbacModule.resources.map((resourceDefinition) => ({
      moduleKey: rbacModule.key,
      moduleName: rbacModule.name,
      ...resourceDefinition,
    }))
  );

export const getAllModuleKeys = () => RBAC_MODULES.map((rbacModule) => rbacModule.key);

