import mongoose from 'mongoose';
import Attendance from '../models/Attendance.js';
import LeaveRequest from '../models/LeaveRequest.js';
import CompanySetting from '../models/CompanySetting.js';
import Notification from '../models/Notification.js';
import { createForbiddenError,createNotFoundError,createValidationError } from '../utils/apiError.js';
import { createdResponse,successResponse } from '../utils/apiResponse.js';
import { asyncHandler } from '../utils/asyncHandler.js';

const employeeScope=(user,field='user')=>user.role==='employee'?{[field]:user.userId}:{};
const owned=async(Model,id,user)=>{if(!mongoose.Types.ObjectId.isValid(id))throw createValidationError('Invalid record id');const record=await Model.findById(id);if(!record)throw createNotFoundError('Record not found');if(user.role==='employee'&&String(record.user)!==String(user.userId))throw createForbiddenError('Access denied');return record;};
const requestIp = (req) => String(req.headers['x-forwarded-for'] || req.ip || req.socket?.remoteAddress || '').split(',')[0].trim().replace('::ffff:', '');
const distanceMeters = (a,b,c,d) => { const r=6371000, p=Math.PI/180, x=(c-a)*p, y=(d-b)*p; const q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2; return 2*r*Math.atan2(Math.sqrt(q),Math.sqrt(1-q)); };
const validatePunch = async (req) => { const config=await CompanySetting.findOne({key:'company'}); const ip=requestIp(req); const latitude=Number(req.body.latitude), longitude=Number(req.body.longitude); if(config?.enableIpValidation && !config.allowedIpAddresses.includes(ip)) throw createForbiddenError('Attendance is only available from an allowed company network'); let location={status:'Not checked',timestamp:new Date()}; if(config?.enableGpsValidation){ if(!Number.isFinite(latitude)||!Number.isFinite(longitude)) throw createValidationError('Location permission is required to punch attendance'); if(config.officeLatitude===null||config.officeLongitude===null) throw createValidationError('Office location has not been configured'); const metres=distanceMeters(latitude,longitude,config.officeLatitude,config.officeLongitude); if(metres>config.allowedGpsRadius) throw createForbiddenError(`You are outside the allowed office radius (${Math.round(metres)}m away)`); location={latitude,longitude,status:'Within allowed radius',timestamp:new Date()}; } else if(Number.isFinite(latitude)&&Number.isFinite(longitude)) location={latitude,longitude,status:'Captured',timestamp:new Date()}; return {config,ip,location}; };

export const AttendanceController={
 mark:asyncHandler(async(req,res)=>{const date=new Date().toISOString().slice(0,10);if(await Attendance.exists({user:req.user.userId,date}))throw createValidationError('Attendance already marked for today');const {config,ip,location}=await validatePunch(req);const record=await Attendance.create({user:req.user.userId,date,checkIn:new Date(),notes:req.body.notes||'',checkInIp:ip,checkInLocation:location,checkInPhoto:config?.enableAttendancePhoto?String(req.body.photo||''): '',requiredWorkingMinutes:Math.round((config?.requiredWorkingHours||8)*60)});res.status(201).json(createdResponse(record,'Punched in successfully'));}),
 list:asyncHandler(async(req,res)=>{const filter=employeeScope(req.user);if(req.query.date)filter.date=req.query.date;if(req.query.month)filter.date={$regex:`^${String(req.query.month).replace(/[^0-9-]/g,'')}`};if(req.query.status)filter.status=req.query.status;res.json(successResponse(await Attendance.find(filter).populate('user','firstName lastName email department').sort({date:-1}),'Attendance history retrieved'));}),
 get:asyncHandler(async(req,res)=>res.json(successResponse(await owned(Attendance,req.params.id,req.user),'Attendance retrieved'))),
 checkout:asyncHandler(async(req,res)=>{const record=await owned(Attendance,req.params.id,req.user);if(record.checkOut)throw createValidationError('Attendance already checked out');const {config,ip,location}=await validatePunch(req);record.checkOut=new Date();record.checkOutIp=ip;record.checkOutLocation=location;record.checkOutPhoto=config?.enableAttendancePhoto?String(req.body.photo||''):'';record.totalWorkingMinutes=Math.max(0,Math.round((record.checkOut-record.checkIn)/60000));record.requiredWorkingMinutes=Math.round((config?.requiredWorkingHours||8)*60);record.status=record.totalWorkingMinutes>=record.requiredWorkingMinutes?'Present':record.totalWorkingMinutes>=record.requiredWorkingMinutes/2?'Half Day':'Absent';await record.save();res.json(successResponse(record,'Punched out successfully'));}),
};

export const LeaveController={
 create:asyncHandler(async(req,res)=>{const{type,startDate,endDate,reason}=req.body;if(!type||!startDate||!endDate||!reason)throw createValidationError('Type, dates, and reason are required');if(new Date(endDate)<new Date(startDate))throw createValidationError('End date must be on or after start date');const record=await LeaveRequest.create({user:req.user.userId,type,startDate,endDate,reason});res.status(201).json(createdResponse(record,'Leave request submitted'));}),
 list:asyncHandler(async(req,res)=>res.json(successResponse(await LeaveRequest.find(employeeScope(req.user)).populate('user','firstName lastName email department').sort({createdAt:-1}),'Leave requests retrieved'))),
 get:asyncHandler(async(req,res)=>res.json(successResponse(await owned(LeaveRequest,req.params.id,req.user),'Leave request retrieved'))),
 review:asyncHandler(async(req,res)=>{if(req.user.role==='employee')throw createForbiddenError('Only administrators can review leave requests');if(!['Approved','Rejected','Pending'].includes(req.body.status))throw createValidationError('Invalid leave status');const record=await owned(LeaveRequest,req.params.id,req.user);record.status=req.body.status;record.reviewNote=req.body.reviewNote||'';await record.save();if(['Approved','Rejected'].includes(record.status)){const from=record.startDate.toISOString().slice(0,10),to=record.endDate.toISOString().slice(0,10);await Notification.create({recipient:record.user,title:`Leave request ${record.status.toLowerCase()}`,message:`Your leave request from ${from} to ${to} has been ${record.status.toLowerCase()}.${record.reviewNote?` ${record.reviewNote}`:''}`,type:record.status==='Approved'?'Success':'Warning'});}res.json(successResponse(record,'Leave request reviewed'));}),
};
