import Payroll from'../models/Payroll.js';import Invoice from'../models/Invoice.js';import UserSetting from'../models/UserSetting.js';import User from'../models/User.js';import Department from'../models/Department.js';import{createForbiddenError,createNotFoundError,createValidationError}from'../utils/apiError.js';import{createdResponse,successResponse}from'../utils/apiResponse.js';import{asyncHandler}from'../utils/asyncHandler.js';
const isHrOrAdmin = (user) => ['admin', 'super_admin'].includes(user?.role) || user?.department === 'HR';
const financial=(Model,label)=>({
 list:asyncHandler(async(req,res)=>res.json(successResponse(await Model.find(!isHrOrAdmin(req.user)?{user:req.user.userId}:{}).populate('user','firstName lastName email department').sort({createdAt:-1}),`${label} retrieved`))),
 get:asyncHandler(async(req,res)=>{const x=await Model.findById(req.params.id).populate('user','firstName lastName email department');if(!x)throw createNotFoundError(`${label} not found`);if(!isHrOrAdmin(req.user)&&String(x.user?._id||x.user)!==String(req.user.userId))throw createForbiddenError('Access denied');res.json(successResponse(x,`${label} retrieved`));}),
 create:asyncHandler(async(req,res)=>{if(!isHrOrAdmin(req.user))throw createForbiddenError(`Employees cannot create ${label.toLowerCase()}`);res.status(201).json(createdResponse(await Model.create(req.body),`${label} created`));}),
 update:asyncHandler(async(req,res)=>{if(!isHrOrAdmin(req.user))throw createForbiddenError('Access denied');const x=await Model.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!x)throw createNotFoundError(`${label} not found`);res.json(successResponse(x,`${label} updated`));}),
 remove:asyncHandler(async(req,res)=>{if(!isHrOrAdmin(req.user))throw createForbiddenError('Access denied');const x=await Model.findByIdAndDelete(req.params.id);if(!x)throw createNotFoundError(`${label} not found`);res.json(successResponse({id:req.params.id},`${label} deleted`));})
});
const payrollData=(body)=>{const number=(key)=>Math.round((Number(body[key])||0)*100)/100;const basicSalary=number('basicSalary');const allowances=number('allowances');const bonus=number('bonus');const incentive=number('incentive');const overtime=number('overtime');const deductions=number('deductions');const salaryAdvance=number('salaryAdvance');const gross=Math.round((basicSalary+allowances+bonus+incentive+overtime)*100)/100;const totalDeduction=Math.round((deductions+salaryAdvance)*100)/100;return {...body,basicSalary,allowances,bonus,incentive,overtime,deductions,salaryAdvance,gross,totalDeduction,net:Math.round(Math.max(0,gross-totalDeduction)*100)/100,month:body.payPeriod||body.month};};
export const PayrollController={...financial(Payroll,'Payroll'),create:asyncHandler(async(req,res)=>{if(!isHrOrAdmin(req.user))throw createForbiddenError('Employees cannot create payroll');if(!req.body.user||!req.body.payPeriod||!req.body.effectiveDate)throw createValidationError('Employee, pay period, and effective date are required');res.status(201).json(createdResponse(await Payroll.create(payrollData(req.body)),'Payroll created'));}),update:asyncHandler(async(req,res)=>{if(!isHrOrAdmin(req.user))throw createForbiddenError('Access denied');const x=await Payroll.findByIdAndUpdate(req.params.id,payrollData(req.body),{new:true,runValidators:true});if(!x)throw createNotFoundError('Payroll not found');res.json(successResponse(x,'Payroll updated'));}),payslip:asyncHandler(async(req,res)=>{const x=await Payroll.findById(req.params.id).populate('user','firstName lastName email department');if(!x)throw createNotFoundError('Payroll not found');if(!isHrOrAdmin(req.user)&&String(x.user._id)!==String(req.user.userId))throw createForbiddenError('Access denied');const cfg=(await import('../models/CompanySetting.js')).default;const company=await cfg.findOne({key:'company'});const rows=[['Employee',`${x.user.firstName||''} ${x.user.lastName||''}`],['Employee ID',x.user._id],['Department',x.user.department||'-'],['Pay Period',x.payPeriod],['Effective Date',x.effectiveDate.toISOString().slice(0,10)],['Basic Salary',x.basicSalary],['Allowances',x.allowances],['Bonus',x.bonus],['Incentive',x.incentive],['Overtime',x.overtime],['Gross Salary',x.gross],['Deductions',x.deductions],['Salary Advance',x.salaryAdvance],['Net Salary',x.net],['Payment Status',x.status]];res.type('html').send(`<!doctype html><html><head><title>Payslip ${x.payPeriod}</title><style>body{font-family:Arial;margin:40px}table{border-collapse:collapse;width:100%}td{border:1px solid #ddd;padding:10px}td:first-child{font-weight:bold;width:45%}</style></head><body><h1>${company?.companyName||'Company'} Payslip</h1><table>${rows.map(([k,v])=>`<tr><td>${k}</td><td>${v}</td></tr>`).join('')}</table></body></html>`);})};export const InvoiceController=financial(Invoice,'Invoice');
export const SettingsController={get:asyncHandler(async(req,res)=>{const x=await UserSetting.findOneAndUpdate({user:req.user.userId},{$setOnInsert:{user:req.user.userId}},{new:true,upsert:true});res.json(successResponse(x,'Settings retrieved'));}),update:asyncHandler(async(req,res)=>{const allowed=['emailNotifications','desktopNotifications','taskReminders','theme','profileVisibility'];const changes=Object.fromEntries(allowed.filter(k=>req.body[k]!==undefined).map(k=>[k,req.body[k]]));const x=await UserSetting.findOneAndUpdate({user:req.user.userId},{$set:changes,$setOnInsert:{user:req.user.userId}},{new:true,upsert:true,runValidators:true});res.json(successResponse(x,'Settings updated'));})};
export const ProfileController={update:asyncHandler(async(req,res)=>{const user=await User.findById(req.user.userId);if(!user)throw createNotFoundError('User not found');if(req.body.department!==undefined){const OFFICIAL_DEPARTMENTS=['HR','Finance','Business Development','Digital Marketing','Video Editor','Tech'];const department=String(req.body.department).trim();if(!OFFICIAL_DEPARTMENTS.includes(department))throw createValidationError('Please select a valid official department');}if(req.body.email!==undefined){const email=String(req.body.email).trim().toLowerCase();if(email!==user.email){const exists=await User.exists({email});if(exists)throw createValidationError('Email already in use');user.email=email;}}const allowed=['firstName','lastName','phone','designation','department','location','emergencyContact'];for(const key of allowed)if(req.body[key]!==undefined)user[key]=String(req.body[key]).trim();if(!user.firstName||!user.lastName)throw createValidationError('First and last name are required');await user.save();res.json(successResponse(user.toJSON(),'Profile updated'));})};
