import { useEffect, useState } from 'react';
import apiClient from '../../../../services/apiClient';
import SuperAdminLayout from '../components/SuperAdminLayout';

const accountName = (account) => `${account.firstName || ''} ${account.lastName || ''}`.trim() || account.email;

export default function Users() {
  const [accounts, setAccounts] = useState([]); const [roles, setRoles] = useState([]); const [selectedRoles, setSelectedRoles] = useState({});
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = async () => { setLoading(true); try { const [accountResponse, roleResponse] = await Promise.all([apiClient.get('/rbac/accounts'), apiClient.get('/rbac/roles')]); const nextAccounts = accountResponse.data.data || []; setAccounts(nextAccounts); setRoles(roleResponse.data.data || []); setSelectedRoles(Object.fromEntries(nextAccounts.map((account) => [account._id, account.rbacRoleId || '']))); setError(''); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load accounts.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const assign = async (account) => { const roleId = selectedRoles[account._id]; if (!roleId) return setError('Select an RBAC role before saving.'); setSaving(account._id); try { await apiClient.patch(`/rbac/accounts/${account.accountType}/${account._id}/role`, { roleId }); setMessage(`Role updated for ${accountName(account)}.`); await load(); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to assign role.'); } finally { setSaving(''); } };
  return <SuperAdminLayout pageTitle="Users Management"><section className="page-card"><div className="page-header-row"><div><div className="section-kicker">Manage</div><h2>Users & Role Assignment</h2><p className="section-subtitle">Assign existing MongoDB-backed RBAC roles to real accounts.</p></div></div>{error && <div className="resource-message error">{error}</div>}{message && <div className="resource-message success">{message}</div>}{loading ? <div className="resource-empty">Loading...</div> : accounts.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Email</th><th>Account type</th><th>Department</th><th>Current role</th><th>Assign role</th><th>Action</th></tr></thead><tbody>{accounts.map((account) => <tr key={`${account.accountType}-${account._id}`}><td>{accountName(account)}</td><td>{account.email}</td><td>{account.accountType}</td><td>{account.department || 'Department not assigned'}</td><td>{account.rbacRoleKey || 'Legacy role'}</td><td><select value={selectedRoles[account._id] || ''} onChange={(event) => setSelectedRoles({ ...selectedRoles, [account._id]: event.target.value })}><option value="">Select role</option>{roles.map((role) => <option key={role._id} value={role._id}>{role.name} ({role.key})</option>)}</select></td><td><button type="button" className="primary-button" disabled={saving === account._id} onClick={() => assign(account)}>{saving === account._id ? 'Saving...' : 'Save role'}</button></td></tr>)}</tbody></table></div> : <div className="resource-empty">No accounts found.</div>}</section></SuperAdminLayout>;
}
